// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int lim = Integer.parseInt(args[0]);
		int overHalf = 0;
		int underHalf = 0;
		for(int i = 0; i < lim; i++) {
			double x = Math.random();
			if(x > 0.5)  overHalf++;
			else underHalf++;
		}
		System.out.println("> 0.5:  " + overHalf);
		System.out.println("<= 0.5: " + underHalf);
		if(overHalf != 0 && underHalf != 0) {
			double ratio = (double) Math.min(overHalf, underHalf) / 
			               (double) Math.max(overHalf, underHalf);
			System.out.printf("Ratio:  " + ratio);
		}
	}
}